### ISSUE TITLE
Update `key` computation logic in `$addToRecentSearchesFn`

### ISSUE THREAD

**Issue by babblebey** [devjargons/jargons.dev#48]
The current logic in the `$addToRecentSearchesFn` function of `/lib/stores/search.js` computes the `key` for recent searches by converting the word to lowercase and replacing spaces with hyphens. This can be improved by using the `normalizeAsUrl` utility function exported from `lib/utils/index.js` to ensure consistency and better handling of special characters.

**Proposed Changes:**

Update the `key` computation in `$addToRecentSearchesFn` from:
```js
const lowercaseKey = word.toLowerCase();
const key = lowercaseKey.includes(" ") ? lowercaseKey.split(" ").join("-") : lowercaseKey;
```
to:
```js
const key = normalizeAsUrl(word);
```

**Related Files:**

- https://github.com/jargonsdev/jargons.dev/blob/main/src/lib/stores/search.js

**Additional Information:**

- Nothing much, feel free to ask any question if you need more clarity on the steps to take 😉

**Comment by chiomalovet** [comment]
Hi i would love to work on this

**Comment by babblebey** [comment]
Have at it @chiomalovet 😉

**Comment by chiomalovet** [comment]
when pushing am i pushing to main or i am creating a new branch?

**Comment by babblebey** [comment]
> when pushing am i pushing to main or i am creating a new branch?
> 

Hey @chiomalovet 

Here's steps to follow.

- Fork the project (Sure you've done this)
- Clone the fork to your machine and run it locally (You done that too)
- Then Create a Branch where you will make your changes and push (this is what you do next 👈🏾)

As soon as you're done with and pushed your changes, come back to the repo here, you will already see a prompt advising you create a pull request against that branch you created.
